# Generated by Django 4.0.4 on 2022-05-09 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dado', '0003_alter_paciente_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenio',
            name='cnpj',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d{2}\\.\\d{3}\\.\\d{3}\\/\\d{4}\\-\\d{2}$', 'CNPJ com formato inválido')]),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='nome_convenio',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator("^[\\w'\\-,.][^0-9_!¡?÷?¿/\\\\+=@#$%ˆ&*(){}|~<>;:[\\]]{2,}$", 'Formato inválido de nome')]),
        ),
        migrations.AlterField(
            model_name='medico',
            name='crm',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='medico',
            name='endereco',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator("^[\\w'\\-,.][^0-9_!¡?÷?¿/\\\\+=@#$%ˆ&*(){}|~<>;:[\\]]{2,}$", 'Formato Inválido')]),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nome',
            field=models.CharField(max_length=170, validators=[django.core.validators.RegexValidator("^[\\w'\\-,.][^0-9_!¡?÷?¿/\\\\+=@#$%ˆ&*(){}|~<>;:[\\]]{2,}$", 'Formato inválido de nome')]),
        ),
    ]
